package main

import (
	"fmt"
	"github.com/MakeNowJust/heredoc/v2"
	"github.com/gookit/goutil/arrutil"
	"github.com/jsumners-nr/nr-node-logviewer/internal/log"
	flag "github.com/spf13/pflag"
	"log/slog"
	"strings"
)

type appFlags struct {
	inputFile string
	logLevel  *LevelFlag
}

var flags = appFlags{}

var usageText = heredoc.Doc(`
	This tool is used to process and explore agent logs generated by the Node.js
	New Relic instrumentation agent.

	The following flags are supported:
`)

func createAndParseFlags(args []string) error {
	flagSet := flag.NewFlagSet("", flag.ContinueOnError)
	flagSet.Usage = func() {
		printUsage(flagSet.FlagUsages())
	}

	flagSet.StringVarP(
		&flags.inputFile,
		"input-file",
		"f",
		"",
		"Path to a newrelic_agent.log file.",
	)

	flags.logLevel = NewLevelFlag()
	flagSet.VarP(
		flags.logLevel,
		"log-level",
		"l",
		"Set the logging level to one of: "+strings.Join(flags.logLevel.allowedValues, ", ")+".",
	)

	// TODO: add a flag that will filter messages based on log type, e.g. "error" logs

	return flagSet.Parse(args[1:])
}

func printUsage(help string) {
	fmt.Println(usageText)
	fmt.Println(help)
}

type LevelFlag struct {
	value         string
	allowedValues []string
}

func NewLevelFlag() *LevelFlag {
	return &LevelFlag{
		allowedValues: []string{"info", "debug", "warn", "error", "trace"},
	}
}

func (l *LevelFlag) String() string {
	return l.value
}

func (l *LevelFlag) Set(value string) error {
	val := strings.TrimSpace(strings.ToLower(value))
	if arrutil.HasValue(l.allowedValues, val) == false {
		return fmt.Errorf("log level must be one of: %s", strings.Join(l.allowedValues, ", "))
	}
	l.value = val
	return nil
}

func (l *LevelFlag) Type() string {
	return "string"
}

func (l *LevelFlag) ToLeveler() slog.Leveler {
	var result slog.Leveler

	switch l.value {
	case "info":
		result = slog.LevelInfo
	case "debug":
		result = slog.LevelDebug
	case "warn":
		result = slog.LevelWarn
	case "error":
		result = slog.LevelError
	case "trace":
		result = log.LevelTrace
	}

	return result
}
